import {useEffect,useRef,useState} from 'react'
import './MinimalVinyl.css'
const works=[
 {no:'01',title:'全景声分轨混音《NUVOLE》',duration:'03:28',seed:5,src:'/assets/media/nuvole-atmos-mix.wav',tag:'全景声分轨混音'},
 {no:'02',title:'2023第五届丹尼大赛入围复赛',duration:'03:45',seed:7,src:'/assets/media/dannie-2022-mix.mp3',tag:'赛事混音作品'},
 {no:'03',title:'原创录混《孤独星球》',duration:'04:07',seed:13,src:'/assets/media/lonely-planet-original-mix.wav',tag:'原创录音与混音'},
 {no:'04',title:'《清白之年》',duration:'04:29',seed:11,src:'/assets/media/innocent-years.mp3',tag:'人声作品'},
 {no:'05',title:'《野有蔓草》',duration:'04:17',seed:3,src:'/assets/media/wild-grass.mp3',tag:'人声作品'}]
const clock=n=>`${String(Math.floor((Number.isFinite(n)?n:0)/60)).padStart(2,'0')}:${String(Math.floor((Number.isFinite(n)?n:0)%60)).padStart(2,'0')}`
function Wave({seed,active}){return <div className={'mv-wave '+(active?'active':'')} aria-hidden="true">{Array.from({length:58},(_,i)=><i key={i} style={{height:`${12+Math.abs(Math.sin((i+seed)*.61)*56)+Math.abs(Math.cos((i+seed)*.19)*18)}%`,animationDelay:`${i*20}ms`}}/>)}</div>}
export default function AudioShowcase(){const[active,setActive]=useState(0),[playing,setPlaying]=useState(false),[elapsed,setElapsed]=useState(0);const audio=useRef(null),work=works[active];useEffect(()=>{setPlaying(false);setElapsed(0);if(audio.current){audio.current.pause();audio.current.currentTime=0}},[active]);useEffect(()=>{if(playing)audio.current?.play().catch(()=>setPlaying(false));else audio.current?.pause()},[playing]);return <section className="audio-showcase shell" id="audio"><div className="mv-head reveal"><p>AUDIO WORKS · SELECTED WORK</p><h2>音频作品</h2></div><div className="mv-player reveal"><div className={'mv-vinyl '+(playing?'spinning':'')} aria-hidden="true"><i/></div><div className="mv-content"><p>{work.tag}</p><h3>{work.title}</h3><Wave seed={work.seed} active={playing}/><div className="mv-controls"><time>{clock(elapsed)} / {work.duration}</time><button type="button" onClick={()=>setPlaying(v=>!v)} aria-label={playing?'暂停':'播放'}>{playing?'Ⅱ':'▶'}</button></div></div><div className="mv-list"><p>其他作品</p><ol>{works.map((item,i)=><li key={item.no} className={i===active?'active':''}><button type="button" onClick={()=>{if(i===active)setPlaying(v=>!v);else setActive(i)}}><span>{item.no}</span><b>{item.title}</b><time>{item.duration}</time></button></li>)}</ol></div></div><audio ref={audio} src={work.src} preload="none" onTimeUpdate={e=>setElapsed(e.currentTarget.currentTime)} onEnded={()=>setPlaying(false)}/></section>}
