import { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'
const videoWorks=[{no:'01',title:'毕业设计《失物招领》CG视频',image:'/assets/media/lost-and-found-poster.jpg',video:'/assets/media/lost-and-found.mp4'},{no:'02',title:'《英雄联盟》CG',image:'/assets/media/league-of-legends-poster.jpg',video:'/assets/media/league-of-legends.mp4'}]
const audioWorks=[{no:'01',title:'何丽雯《野有蔓草》',duration:'04:17',seed:3,src:'/assets/media/wild-grass.mp3'},{no:'02',title:'2022丹尼大赛混音组参赛作品',duration:'03:45',seed:7,src:'/assets/media/dannie-2022-mix.mp3'},{no:'03',title:'何丽雯《清白之年》',duration:'04:29',seed:11,src:'/assets/media/innocent-years.mp3'}]
const experience=[['2023.09 — 至今','上海微创软件有限公司','腾讯全民K歌业务线 · 产品运营','负责会员权益、音效内容与产品功能运营，覆盖调音台、人声增强、AI 降噪、均衡及母带模板；协同研发、设计、算法和内容团队推进功能配置、验收与上线。'],['2023.01 — 2023.03','广西民族音乐博物馆','录音师','负责民族乐器现场录音，并独立完成素材剪辑、降噪和混音处理，为省级创新项目提供音频样本支持。'],['2022.10 — 2022.12','南宁广播电视台','后期编辑','完成城市文化系列音频的剪辑、音效设计与氛围铺垫，并参与内容审核和新媒体发布协作。']]
function Waveform({seed,active}){return <div className={'waveform '+(active?'active':'')} aria-hidden="true">{Array.from({length:44},(_,i)=><i key={i} style={{height:`${8+Math.abs(Math.sin((i+seed)*.73)*30)+Math.abs(Math.cos((i+seed)*.29)*16)}%`,animationDelay:`${i*28}ms`}}/>)}</div>}
function AudioCard({work,playing,onPlay}){const audio=useRef(null),[elapsed,setElapsed]=useState(0);useEffect(()=>{if(playing){audio.current?.play()}else{audio.current?.pause()}},[playing]);const clock=n=>{const m=Math.floor(n/60),s=Math.floor(n%60);return `:`};return <article className={'audio-card '+(playing?'is-playing':'')}><audio ref={audio} src={work.src} preload="metadata" onTimeUpdate={e=>setElapsed(e.currentTarget.currentTime)} onEnded={onPlay}/><div className="audio-top"><strong>{work.no}</strong><button className="play" onClick={onPlay}><span>{playing?'Ⅱ':'▶'}</span></button><Waveform seed={work.seed} active={playing}/></div><div className="audio-meta"><span>{work.title}</span><time>{clock(elapsed)} / {work.duration}</time></div></article>}
function App(){const[playing,setPlaying]=useState(null),[menuOpen,setMenuOpen]=useState(false),[selectedVideo,setSelectedVideo]=useState(null);const videoDialog=useRef(null);useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);const openVideo=work=>{setSelectedVideo(work);videoDialog.current?.showModal()};return <main>
<header className="site-head shell"><a className="brand" href="#work"><span className="brand-wave">▮▯▮▯</span><b>SOUND DESIGNER</b></a><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?'关闭':'菜单'}</button><nav className={menuOpen?'open':''}><a className="active" href="#work">作品</a><a href="#about">关于</a><a href="#resume">履历</a><a href="#contact">联系</a></nav></header>
<section className="sound-section shell" id="work"><div className="hero-title reveal"><p>PORTFOLIO · 2026</p><h1>音效设计</h1><div className="mic"/></div><div className="video-grid">{videoWorks.map(work=><article className="video-card reveal" key={work.no}><button className="video-cover" onClick={()=>openVideo(work)}><img src={work.image} alt=""/><span className="video-shade"/><span className="play large">▶</span></button><div className="video-meta"><b>{work.no}</b><h2>{work.title}</h2><span>SOUND DESIGN</span></div></article>)}</div></section>
<section className="audio-section shell" id="audio"><div className="section-title reveal"><h2>音频作品</h2><span className="signal-line"/></div><div className="audio-grid">{audioWorks.map((work,i)=><AudioCard key={work.no} work={work} playing={playing===i} onPlay={()=>setPlaying(playing===i?null:i)}/>)}</div></section>
<section className="about-section shell reveal" id="about"><div className="about-photo"><img src="/assets/portrait.jpg" alt="李文赫职业照"/></div><div className="about-copy"><p className="section-kicker">ABOUT · LI WENHE</p><h2>让声音成为<br/>体验的一部分。</h2><p>广西艺术学院录音艺术专业，拥有腾讯全民K歌业务线产品运营经验。专注声音设计、音频内容运营与 AI 内容创作，擅长把听觉细节、产品逻辑和用户体验连接起来。</p><div className="stats"><div><b>500+</b><span>音效 Demo</span></div><div><b>20+</b><span>人声音效</span></div><div><b>134.6W</b><span>单条最高播放</span></div></div></div></section>
<section className="resume-section shell" id="resume"><div className="section-title reveal"><h2>个人履历</h2><span className="signal-line"/></div><div className="resume-grid"><aside className="resume-aside reveal"><p className="section-kicker">EDUCATION</p><h3>广西艺术学院</h3><p>录音艺术专业<br/>2019.09 — 2023.06</p><div className="tool-list">Pro Tools · Logic · Cubase · Ableton Live · Nuendo · Wwise · Suno AI</div></aside><div className="timeline">{experience.map((item,i)=><article className="resume-item reveal" key={item[1]}><span>0{i+1}</span><time>{item[0]}</time><div><h3>{item[1]}</h3><h4>{item[2]}</h4><p>{item[3]}</p></div></article>)}</div></div></section>
<footer className="contact-section shell" id="contact"><p className="section-kicker">CONTACT</p><h2>一起创造<br/>值得被听见的作品。</h2><a className="email" href="mailto:hello@liwenhe.design">hello@liwenhe.design <span>↗</span></a><div className="footer-line"><span>© 2026 LI WENHE</span><span>SHANGHAI / CHINA</span><a href="#work">返回顶部 ↑</a></div></footer>
<dialog ref={videoDialog} className="video-dialog" onClose={()=>setSelectedVideo(null)}><button onClick={()=>videoDialog.current?.close()}>×</button><video key={selectedVideo?.video} controls autoPlay poster={selectedVideo?.image}><source src={selectedVideo?.video} type="video/mp4"/></video><p>{selectedVideo?.title}</p></dialog>
</main>}
createRoot(document.getElementById('root')).render(<App/>)


